on:
  pull_request:
  #   branches:
  #   - master

  push:
      branches:
        - main
        - master

jobs:

  build:
    runs-on: ubuntu-18.04
    env:
      GOPRIVATE: github.com/credential-did
      GH_ACCESS_TOKEN: ${{ secrets.DIUCICD_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Inject insteadOf configuration for private repo
      run: |
        git config --global url."https://${{ secrets.DIUCICD_TOKEN }}:x-oauth-basic@github.com/credential-did".insteadOf "https://github.com/credential-did"
        # test
        GOPRIVATE=github.com/credential-did/verifiable-credential-go-sdk go get -v github.com/credential-did/verifiable-credential-go-sdk


